//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tccalc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tccalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 元素描述文件版本： 的本地化字符串。
        /// </summary>
        internal static string asver {
            get {
                return ResourceManager.GetString("asver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算错误咯！【是不是步数写错了呢？】 的本地化字符串。
        /// </summary>
        internal static string calcerror {
            get {
                return ResourceManager.GetString("calcerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貌似没有可以连接的方法呢，是否增大一步来尝试连接呢？ 的本地化字符串。
        /// </summary>
        internal static string cannotfindlink {
            get {
                return ResourceManager.GetString("cannotfindlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到连接方法 的本地化字符串。
        /// </summary>
        internal static string cannotfindlink_ {
            get {
                return ResourceManager.GetString("cannotfindlink_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的元素有错误，请确认开始及结束元素都选择了一个哦 的本地化字符串。
        /// </summary>
        internal static string checkas {
            get {
                return ResourceManager.GetString("checkas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑收起高级选项↑ 的本地化字符串。
        /// </summary>
        internal static string closead {
            get {
                return ResourceManager.GetString("closead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少应当存在一个结果 的本地化字符串。
        /// </summary>
        internal static string noresult {
            get {
                return ResourceManager.GetString("noresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string nullas {
            get {
                return ResourceManager.GetString("nullas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↓展开高级选项↓ 的本地化字符串。
        /// </summary>
        internal static string openad {
            get {
                return ResourceManager.GetString("openad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pic {
            get {
                object obj = ResourceManager.GetObject("pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string prompt {
            get {
                return ResourceManager.GetString("prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共有 {0} 组结果，步数为 {1} 的本地化字符串。
        /// </summary>
        internal static string resultwindowtitle {
            get {
                return ResourceManager.GetString("resultwindowtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择： 的本地化字符串。
        /// </summary>
        internal static string selectedas {
            get {
                return ResourceManager.GetString("selectedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↓已选择： 的本地化字符串。
        /// </summary>
        internal static string selecteddown {
            get {
                return ResourceManager.GetString("selecteddown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑已选择： 的本地化字符串。
        /// </summary>
        internal static string selectedup {
            get {
                return ResourceManager.GetString("selectedup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能排除起始元素和结束元素哦，请确认一下排除元素列表 的本地化字符串。
        /// </summary>
        internal static string startendasrequested {
            get {
                return ResourceManager.GetString("startendasrequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入步数哦 的本地化字符串。
        /// </summary>
        internal static string steprequested {
            get {
                return ResourceManager.GetString("steprequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步数不是数字哦 的本地化字符串。
        /// </summary>
        internal static string stepshouldbenumber {
            get {
                return ResourceManager.GetString("stepshouldbenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步数太小了，请确保步数在0以上哦 的本地化字符串。
        /// </summary>
        internal static string stepshouldbepositivenum {
            get {
                return ResourceManager.GetString("stepshouldbepositivenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步数太大了，神秘时代4没有步数9以上的连接哦，确定要继续计算吗？【时间可能会非常长】 的本地化字符串。
        /// </summary>
        internal static string steptoobig {
            get {
                return ResourceManager.GetString("steptoobig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该版本的元素描述文件有更新了，需要下载吗？ 的本地化字符串。
        /// </summary>
        internal static string updateavailable {
            get {
                return ResourceManager.GetString("updateavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作完成！ 的本地化字符串。
        /// </summary>
        internal static string updatecompleted {
            get {
                return ResourceManager.GetString("updatecompleted", resourceCulture);
            }
        }
    }
}
