//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 元素描述文件版本： 的本地化字符串。
        /// </summary>
        internal static string AspectDescriptionFileVersion {
            get {
                return ResourceManager.GetString("AspectDescriptionFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 计算错误咯！【是不是步数写错了呢？】 的本地化字符串。
        /// </summary>
        internal static string CalculationError {
            get {
                return ResourceManager.GetString("CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貌似没有可以连接的方法呢，是否增大一步来尝试连接呢？ 的本地化字符串。
        /// </summary>
        internal static string CannotFindLink {
            get {
                return ResourceManager.GetString("CannotFindLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到连接方法 的本地化字符串。
        /// </summary>
        internal static string CannotFindLink_ {
            get {
                return ResourceManager.GetString("CannotFindLink_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的元素有错误，请确认开始及结束元素都选择了一个哦 的本地化字符串。
        /// </summary>
        internal static string CheckAspect {
            get {
                return ResourceManager.GetString("CheckAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑收起高级选项↑ 的本地化字符串。
        /// </summary>
        internal static string CloseAdvance {
            get {
                return ResourceManager.GetString("CloseAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 于第 {0} 行遇到无效的元素描述 的本地化字符串。
        /// </summary>
        internal static string InvalidAspectDescription {
            get {
                return ResourceManager.GetString("InvalidAspectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的设置文件 的本地化字符串。
        /// </summary>
        internal static string InvalidSettingFile {
            get {
                return ResourceManager.GetString("InvalidSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少应当存在一个结果 的本地化字符串。
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string NullAspect {
            get {
                return ResourceManager.GetString("NullAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↓展开高级选项↓ 的本地化字符串。
        /// </summary>
        internal static string OpenAdvance {
            get {
                return ResourceManager.GetString("OpenAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共有 {0} 组结果，步数为 {1} 的本地化字符串。
        /// </summary>
        internal static string ResultWindowTitle {
            get {
                return ResourceManager.GetString("ResultWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择： 的本地化字符串。
        /// </summary>
        internal static string SelectedAspect {
            get {
                return ResourceManager.GetString("SelectedAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↓已选择： 的本地化字符串。
        /// </summary>
        internal static string SelectedDown {
            get {
                return ResourceManager.GetString("SelectedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑已选择： 的本地化字符串。
        /// </summary>
        internal static string SelectedUp {
            get {
                return ResourceManager.GetString("SelectedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能排除起始元素和结束元素哦，请确认一下排除元素列表 的本地化字符串。
        /// </summary>
        internal static string StartEndAspectRequested {
            get {
                return ResourceManager.GetString("StartEndAspectRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入步数哦 的本地化字符串。
        /// </summary>
        internal static string StepRequested {
            get {
                return ResourceManager.GetString("StepRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步数不是数字哦 的本地化字符串。
        /// </summary>
        internal static string StepShouldBeNumber {
            get {
                return ResourceManager.GetString("StepShouldBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步数太小了，请确保步数在0以上哦 的本地化字符串。
        /// </summary>
        internal static string StepShouldBePositiveNum {
            get {
                return ResourceManager.GetString("StepShouldBePositiveNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步数太大了，神秘时代4没有步数9以上的连接哦，确定要继续计算吗？【时间可能会非常长】 的本地化字符串。
        /// </summary>
        internal static string StepTooBig {
            get {
                return ResourceManager.GetString("StepTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该版本的元素描述文件有更新了，需要下载吗？ 的本地化字符串。
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作完成！ 的本地化字符串。
        /// </summary>
        internal static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
    }
}
